spring:
  application:
    name: notification-service
  cloud:
      stream:
        bindings:
          notificationChannel:
            destination: notification.req
            binder: local_rabbit
          notificationReplyChannel:
            destination: notification.resp
            binder: local_rabbit
        binders:
          local_rabbit:
            type: rabbit
            environment:
              spring:
                rabbitmq:
                  host: localhost
                  port: 5672
                  username: guest
                  password: guest
                  virtual-host: /


server:
  port: 7799
  servlet:
    context-path: /notification-service

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.server.host}:${eureka.server.port}/discovery/eureka
    fetch-registry: true
  server:
    host: localhost
    port: 8761
