spring:
  application:
    name: voucher-service
  datasource:
    url: jdbc:mysql://localhost:3306/voucher_data?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: P@ssw0rd
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  cloud:
      stream:
        bindings:
          notificationReplyChannel:
            destination: notification.resp
            binder: local_rabbit
          notificationChannel:
            destination: notification.req
            binder: local_rabbit
        binders:
          local_rabbit:
            type: rabbit
            environment:
              spring:
                rabbitmq:
                  host: localhost
                  port: 5672
                  username: guest
                  password: guest
                  virtual-host: /


server:
  port: 7777
  servlet:
    context-path: /voucher-service
  error:
    include-message: ALWAYS

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.server.host}:${eureka.server.port}/discovery/eureka
    fetch-registry: true
  server:
    host: localhost
    port: 8761

resilience4j.timelimiter:
  instances:
    3rdService:
      timeoutDuration: 6s
      cancelRunningFuture: false